/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 30 05:00:16 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.Stack;
import java.util.NoSuchElementException;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Stack_ESTest extends Stack_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      stack0.iterator();
      stack0.push(stack0);
      Stack<String> stack1 = new Stack<String>();
      stack1.spliterator();
      stack1.push((String) null);
      stack1.isEmpty();
      stack1.peek();
      // Undeclared exception!
      try { 
        stack1.toString();
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.push("U05?R;PH");
      stack0.isEmpty();
      Stack<Object> stack1 = new Stack<Object>();
      // Undeclared exception!
      try { 
        stack1.forEach((Consumer<? super Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.push("xhF.&$a LZz");
      stack0.size();
      stack0.iterator();
      Stack<Integer> stack1 = new Stack<Integer>();
      // Undeclared exception!
      try { 
        stack1.peek();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Stack underflow
         //
         assertThrownBy("edu.osu.cs362.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.toString();
      Stack<Object> stack1 = new Stack<Object>();
      stack1.iterator();
      stack0.size();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      stack0.isEmpty();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      // Undeclared exception!
      try { 
        stack0.peek();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Stack underflow
         //
         assertThrownBy("edu.osu.cs362.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      stack0.toString();
      stack0.push(stack0);
      stack0.iterator();
      stack0.pop();
      stack0.peek();
      stack0.size();
      Stack<String> stack1 = new Stack<String>();
      // Undeclared exception!
      try { 
        stack1.pop();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Stack underflow
         //
         assertThrownBy("edu.osu.cs362.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.push("Wx!o!+qh\u0005LM#:<\"PO");
      // Undeclared exception!
      try { 
        stack0.toString();
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Stack<Integer> stack0 = new Stack<Integer>();
      // Undeclared exception!
      try { 
        stack0.pop();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Stack underflow
         //
         assertThrownBy("edu.osu.cs362.Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      stack0.iterator();
      stack0.toString();
      stack0.iterator();
      stack0.toString();
      assertEquals(0, stack0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.iterator();
      stack0.toString();
      assertEquals(0, stack0.size());
  }
}
